apiVersion: v1
kind: Service
metadata:
  name: svc-pagamento-app
spec:
  type: LoadBalancer
  selector:
    app: pagamento-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30002  # Port on each node
    targetPort: 3334